### PR TITLE
new macaddr & subnetcalc submodule

### PR DESCRIPTION
**Pull request by Bierchermuesli**
I think a submodule is more tidy - but I can also merge in to main branch. Thanks!

### CODE REVIEW

**Comment by Bierchermuesli** [comment]
new IPv4/IPv6 Subnetcal as submodule, Thanks

**Review by idkCpp — COMMENTED** [review]
@ManuelSchneid3r what do you want here to be reviewed?

I mean the extension looks fine. There are some things I could comment on, but this is rather unpractical

**Comment by ManuelSchneid3r** [comment]
It's about peer reviewing. If several reviewers approve I can just merge.

**Comment by ManuelSchneid3r** [comment]
0.18 is out. Please check the [new api](https://github.com/albertlauncher/plugins/blob/master/python/README.md) . Do you mind to volunteer as a maintainer for the plugin?

**Comment by Bierchermuesli** [comment]
I updated the macaddr plugin. can you check if it fits?

is GIT submodules still the way to go?

**Comment by ManuelSchneid3r** [comment]
cool! nowadays I'd rather tend to not have submodules. Colaboration/reviewing is not that easy with submodules and eventual changes of maintainers are more complicated. Unless you have some weird license i'd recommend to just add code.

**Pull request closed without merging**
