### PR TITLE
feat: add node js evaluator

### PR DESCRIPTION
**Pull request by devhammed**
I added a plugin to evaluate JavaScript expressions using Node.js!

Screenshot from 2020-06-21 07-02-18

Screenshot from 2020-06-21 07-18-08

### CODE REVIEW

**Comment by ManuelSchneid3r** [comment]
why did you close this one? looks cool.

**Comment by devhammed** [comment]
> why did you close this one? looks cool.

I saw that contributions are not being accepted here, that there is another community repository.

**Comment by ManuelSchneid3r** [comment]
the community repo was intended to work on its own by the comnunity. however nobody is willing to review code so the PR do not get the min 3 reviews to be automatically merged. 🤷‍♂️  

well yes send it here

**Comment by devhammed** [comment]
> the community repo was intended to work on its own by the comnunity. however nobody is willing to review code so the PR do not get the min 3 reviews to be automatically merged. 
> 
> well yes send it here

Done, it is available here: https://github.com/albertlauncher/python/pull/88

**Comment by ManuelSchneid3r** [comment]
thank you. ill review soon. just have to go through these hundreds of notifications.

**Pull request closed without merging**
