### PR TITLE
Added vscode plugin as submodule

### PR DESCRIPTION
**Pull request by mparati31**

### CODE REVIEW

**Comment by Sharsie** [comment]
@mparati31 Would you consider adding the support for vscode extension Project Manager? I'm no python wizzard, so I'd be in favor of your vscode plugin over mine, though I make a heavy use of the PM extension myself.
The code I wrote for it is here: https://github.com/Sharsie/albertlauncher-vscode-projects/blob/main/__init__.py#L143-L191

I would also welcome [accent normalization](https://github.com/Sharsie/albertlauncher-vscode-projects/blob/main/__init__.py#L49-L51) on the query and recents/PM results, so stuff like `È` can be searched with `e`

If you like, I can eventually PR these changes on top of your repository, although I don't come from the python world.

**Comment by mparati31** [comment]
@Sharsie Good idea, I'll be adding support for the PM extension and accent normalization in the next few days.

**Comment by ManuelSchneid3r** [comment]
Actually because reviewing is such a pain using submodules I'd recommend to not use them. 0.18 is out. please check the new api https://github.com/albertlauncher/plugins/blob/master/python/README.md

**Comment by ManuelSchneid3r** [comment]
@mparati31 do you still plan to get this merged?

**Comment by ManuelSchneid3r** [comment]
Closing due to conflicts. Please join the discussoin at #114.

**Pull request closed without merging**
