### PR TITLE
Clipboard snippets

### PR DESCRIPTION
**Pull request by ewasser**
This clipboard archive will give you access to your clipboard favorites. The selected value will be pasted into the clipboard, ready for the next `CTRL-v`.

The snippets will be maintained in a little configuration file `~/.config/albert/org.albert.extension.clipboard-snippets/clipboard-snippets.yaml`. That file can be edited with a simple text editor.

The file will be autocreated at the first startup with some little examples. The editor can be called as action if the search string is empty.

The activation for this plugin is `cp`.

### CODE REVIEW

**Comment by ManuelSchneid3r** [comment]
:thinking: whats the problem with the snippets (formerly kvstore)???

**Comment by ewasser** [comment]
That's funny. I've read the description of the plugin and this description

> This extension lets you store values by key and look them up by the key. Trigger the extension by typing "kv " to show the entries. Further characters act as a filter on the keys. Note that the lookup works without the trigger too. Type "kv set <key> <value>" or "kv unset <key>" to set and unset 
mappings.

doesn't ring the clipboard bell in my head. It sounds pretty obvious in the hindsight. You can close this merge request.

**Comment by ewasser** [comment]
There is one thing that my extension can do. It can execute the given clipboard snippet on demand. For example the key-value pair

    timestamp => `date +"%Y-%m-%d %H:%M:%S`

will execute the command `date +"%Y-%m-%d %H:%M:%S` (because of the backticks) and stores the current timestamp in the clipboard.

**Comment by ManuelSchneid3r** [comment]
I am sorry but I cant merge this. This is not really mainstream. Its a mixture of the snippets and terminal extension. Snippets are intendend to be text of any size. You would not execute you lorem ipsum paragraph.
I dont want to overload the app with extensions of any kind. I try to keep the UX crisp.

**Pull request closed without merging**
