### PR TITLE
Currency2.py - used by exch2

### PR DESCRIPTION
**Pull request by TheBlackKoala**
finance.google blocks me (and assumedly others as well) so Currency2 uses xe.com. The file is changed minimally from the original Currency.py.

### CODE REVIEW

**Comment by ManuelSchneid3r** [comment]
Please pull. This is the older version. The new one allows several provoiders. You could add yours there.

**Comment by ManuelSchneid3r** [comment]
@TheBlackKoala are you still interested in adding xe as provider?

**Comment by TheBlackKoala** [comment]
No the new version works perfectly well :) thank you very much

Best wishes Tor
I am not currently at my main setup so please excuse any mistskes or inconsistencies

On 20 Aug 2018 12:27 pm, Manuel Schneider <notifications@github.com> wrote:

@TheBlackKoala<https://github.com/TheBlackKoala> are you still interested in adding xe as provider?

**Comment by ManuelSchneid3r** [comment]
Okay. 👌

**Pull request closed without merging**
