### PR TITLE
1Password Extension

### PR DESCRIPTION
**Pull request by koenhendriks**
I've created a 1Password extension that allows quick copy of passwords or 2FA. 

See the source code and readme at https://github.com/koenhendriks/1password-albert

Relates to https://github.com/albertlauncher/albert/discussions/1106

### CODE REVIEW

**Comment by c4pQ** [comment]
I'm not sure it's the right way to add an extension to the project - you suggest the whole repository as a submodule.

I'd suggest linking a particular hash, that's verified by the albert's team.

What do you think?

**Comment by ManuelSchneid3r** [comment]
Actually because reviewing is such a pain using submodules I'd recommend to not use them. 0.18 is out. please check the new api https://github.com/albertlauncher/plugins/blob/master/python/README.md

**Comment by ManuelSchneid3r** [comment]
@koenhendriks are you still interested in getting this plugin upstream?

**Comment by ManuelSchneid3r** [comment]
I am going to close this PR. It is not that I dont want this to be shipped upstream, but, as is, it cant be merged due to conflicts. Users/devs get the impression that I dont want to merge plugins, probably simply due to the amount of open PRs.  Also it's cumbersome for me to repeatedly iterate all these abandoned and stale PRs. Note that I am still interested in merging an up to date version of this plugin and I still get notifications. So if you want something to happen leave a comment or simply open a new PR.

**Comment by koenhendriks** [comment]
This extension only works on Albert <= 17 and I'm not in a lot of time to update it.

No worries for closing the PR, thanks for the heads up.

**Pull request closed without merging**
