### PR TITLE
Update jetbrains plugin

### PR DESCRIPTION
**Pull request by mqus**
This updates the submodule hash to point to the newest version, which is compatible to v0.4 of the API.

### CODE REVIEW

**Review by tomsquest — APPROVED** [review]

**Comment by tomsquest** [comment]
Tested locally. Everything is fine. :+1: 
Good to merge.

**Comment by mqus** [comment]
Please review @alswl, @barbUK or @bergercookie . This plugin is not working for almost a year now and really needs this update. I was told that making this a submodule would simplify updates but so far this has not worked out at all.

**Comment by bergercookie** [comment]
Haven't tested it since I don't use jetbrains, but the changes look sensible.

**Review by bergercookie — APPROVED** [review]

**Comment by ManuelSchneid3r** [comment]
0.18 is out. Please check the [new api](https://github.com/albertlauncher/plugins/blob/master/python/README.md) . Do you mind to volunteer as a maintainer for the plugin?

**Comment by mqus** [comment]
See https://github.com/mqus/jetbrains-albert-plugin/pull/5 :)

**Comment by ManuelSchneid3r** [comment]
I hope its not too much of a hassle but can you please add without the submodule?

**Comment by ManuelSchneid3r** [comment]
[Rationale](https://github.com/albertlauncher/python/pull/129#issuecomment-1372732334)

**Comment by ManuelSchneid3r** [comment]
@mqus do mind to maintain it if I move it in the repo?

**Comment by ManuelSchneid3r** [comment]
> @ManuelSchneid3r I can also step up to maintain it. I did a complete rewrite of the plugin. The PR is on @mqus [side on his repo](https://github.com/mqus/jetbrains-albert-plugin/pull/6). I think I will submit it here directly if no answer.

Actually I'd prefer this because I want jo join the party to get it working on MacOS

**Comment by mqus** [comment]
Sorry, IRL stuff. Yes, I'm also in favor of maintaining it here. Let me open a PR.

**Pull request closed without merging**
