### PR TITLE
Fix JetBrains plugin for newer IDEs

### PR DESCRIPTION
**Pull request by lalloni**

### CODE REVIEW

**Comment by mqus** [comment]
This is a duplicate of #70. Thank you for your effort but this was already proposed for a fix. Sadly, the albert project seems unmaintained right now.

**Comment by lalloni** [comment]
Really? It's so sad... I've just recently started to use it...

**Comment by tomsquest** [comment]
Yes, sad truth. Lots of work involved from the creator (lots of lots).
But still, Albert is working like a charm and really great.

**Comment by lalloni** [comment]
There's no initiative to hand over maintenance to the community?

**Comment by mqus** [comment]
> There's no initiative to hand over maintenance to the community?

I think that there isn't really anyone who stepped up to fork/maintain the main application. Then there is also the issue with the licensing...(https://github.com/albertlauncher/albert/issues/765)

What I initially came here for: I made a few more fixes to the plugin and am now hosting the plugin here: https://github.com/mqus/jetbrains-albert-plugin

**Comment by ManuelSchneid3r** [comment]
this may raise KeyError, but somebody else did the same with a check meanwhile.

**Pull request closed without merging**
