### PR TITLE
[gnome-calculator:1.0] Release plugin

### PR DESCRIPTION
**Pull request by Ghurir**
I couldn't find any app launcher with a calculator function as advanced as the gnome calculator, so I wrote this simple plugin for myself. And I wanted to share it if you liked it.

This plugin executes the 'gnome-calculator' command and returns the result.

#### Working Features:
* Basic arithmitics {10*(4+5)^2 = 810   |   9 mod 5   |   140+15%}
* Functions {sqrt(2;3)   |   log(4;3)   |   sin5}
* Conversion {30 gallon to l = 113,56   |   1m**3 in l = 1000   |   5 deg in rad = 0,087}

#### Doesn't work
* Currency conversion
* several functions such as 'rand' and subscript (to indicate base: 1010₂)

### CODE REVIEW

**Comment by ManuelSchneid3r** [comment]
Have you seen libqalculate?

**Comment by Ghurir** [comment]
> Have you seen libqalculate? I mean the calculator shipped with Albert.

libqalculate didn't do conversions without entering '=', and while searching for how to fix it I forgot it existed 🫠 :P

**Comment by ManuelSchneid3r** [comment]
> libqalculate didn't do conversions without entering '=',

intentionally iirc. because it accepts a lot of input. which gives undesired output in the global queries. 

we could add an option though i guess for those who want it

**Comment by ManuelSchneid3r** [comment]
https://github.com/albertlauncher/plugins/commit/3db3deddfe99b32e429ea63350dfd0af4af8a09e

**Comment by ManuelSchneid3r** [comment]
does 0.26.3 serve your purposes?

**Comment by Ghurir** [comment]
Yes, thank you 🌹

**Pull request closed without merging**
