### PR TITLE
feat(jetbrains-project): add RustRover editor

### PR DESCRIPTION
**Pull request by vmaerten**
Jetbrains released a new editor for Rust, called RustRover

### CODE REVIEW

**Comment by ManuelSchneid3r** [comment]
lgtm. what do you think @mqus @tomsquest?

**Comment by tomsquest** [comment]
Hi @vmaerten ,

Thanks for the addition.

Couple checks before giving it a go:
1. Can you confirm the config dir and binaries? (ie. the plugin is working for this new editor)
2. I found an SVG with the `beta` tag, on it. Would you mind replacing your by it? This would avoid @ManuelSchneid3r to merge a second PR when the icon will be updated
Here is [the link](https://www.jetbrains.com/resources/eap/) (the svg is in the source of the page)

**Comment by vmaerten** [comment]
1. I've updated the plugin locally, I can confirm it's working.
image
Screenshot_2023-10-02_14-17-43

2.  Yes, I'll update the svg

**Review by tomsquest — APPROVED** [review]

**Comment by tomsquest** [comment]
Excellent. Thx @vmaerten ! :+1: 

LGTM

**Comment by ManuelSchneid3r** [comment]
Please also increase the minor version

**Comment by vmaerten** [comment]
@ManuelSchneid3r It's done. It's now on version 1.6

**Comment by ManuelSchneid3r** [comment]
👍

**Pull request merged**
