### PR TITLE
Add Window Switcher extension

### PR DESCRIPTION
**Pull request by benedictdudel**
This extension can interact with a EWMH/NetWM compatible X Window Manager.

Usage:
- list and filter all windows by typing `wm <filter>`
- list and filter desktops by typing `wm desktop <filter>`
- Default action:
  - switch to window/desktop
- Alternative actions:
  - close window

Dependencies:
- wmctrl
- xprop

### CODE REVIEW

**Comment by dufferzafar** [comment]
Tried this on KDE Neon (Ubuntu 16.04 Xenial with KDE) with Albert 0.14

The icons & names are not proper for all apps/windows.

Here's a screenshot:
image

**Comment by harindu95** [comment]
I think you should try to get the WM_CLASS of the window instead of using title as the icon name.
Check this [answer](https://askubuntu.com/a/483642) on SO.

**Comment by nullstrike** [comment]
This doesn't work on Ubuntu 17.10 using compiz window manager

**Comment by ManuelSchneid3r** [comment]
Conversation locked until [poll](https://github.com/albertlauncher/albert/issues/123#issuecomment-413868346) finished.

**Comment by ManuelSchneid3r** [comment]
Please continue any discussion here: https://github.com/orgs/albertlauncher/discussions/1299

**Pull request closed without merging**
