### PR TITLE
Reverso Context Transaltor

### PR DESCRIPTION
**Pull request by gitadum**
Translates words or short expressions between 15 languages.
This extension uses [Reverso Context](https://context.reverso.net/traduction/), a quite powerful online translator, via this [Python API](https://pypi.org/project/Reverso-API/).
Inspired by @ManuelSchneid3r's Google Translate extension.

To use it, type the trigger `rev` in your albert launcher, followed by the source language letter-code, the target language letter code, then the text you wanna translate.

The API is quite reliable and responsive :)

List of available languages (and their letter-codes):
* Arabic (`ar`)
* Chinese (`zh`)
* Dutch (`nl`)
* English (`en`)
* French (`fr`)
* German (`de`)
* Hebrew (`he`)
* Italian (`it`)
* Japanese (`ja`)
* Polish (`pl`)
* Portuguese (`pt`)
* Romanian (`ro`)
* Russian (`ru`)
* Spanish (`es`)
* Turkish (`tr`)

**Update from June 2023**
- New languages available:
  * Korean (`ko`) (works only with English so far)
  * Ukrainian (`uk`)

### CODE REVIEW

**Comment by ManuelSchneid3r** [comment]
0.18 is out. Please check the [new api](https://github.com/albertlauncher/plugins/blob/master/python/README.md) . Do you mind to volunteer as a maintainer for the plugin?

**Comment by gitadum** [comment]
@ManuelSchneid3r I don't mind at all!

**Comment by ManuelSchneid3r** [comment]
Cool 👍

**Comment by ManuelSchneid3r** [comment]
@gitadum are you still interested in getting this plugin upstream?

**Comment by ManuelSchneid3r** [comment]
I am going to close this PR. It is not that I dont want this to be shipped upstream, but, as is, it cant be merged due to conflicts. Users/devs get the impression that I dont want to merge plugins, probably simply due to the amount of open PRs.  Also it's cumbersome for me to repeatedly iterate all these abandoned and stale PRs. Note that I am still interested in merging an up to date version of this plugin and I still get notifications. So if you want something to happen leave a comment or simply open a new PR.

**Comment by gitadum** [comment]
Hello,
I updated my repo with upstream
Would you like me to open a new PR?

**Comment by gitadum** [comment]
I'll make the changes required to make it cope with lattest api standard (write a plugin class etc)

**Comment by ManuelSchneid3r** [comment]
I'll close unmergable PRs to reduce mental load. 😄reopen if it is ready.

**Pull request closed without merging**
