### PR TITLE
Migrating VPN and Timer plugin to albert v18.x

### PR DESCRIPTION
**Pull request by uztnus**

### CODE REVIEW

**Comment by roman-acumen** [comment]
@ManuelSchneid3r can you pls review

**Comment by ManuelSchneid3r** [comment]
@roman-acumen I am currently working on some bigger changes in the core app. Then there are these dozens of reviews I have in the pipeline. You could be of help as well. afaik everybody can comment/review pull requests.

**Comment by ManuelSchneid3r** [comment]
#155

**Comment by ManuelSchneid3r** [comment]
@uztnus next time before send PR make sure that the extensions are polished. I thought i could "quickly" merge this, but ended up rewriting the entire ext. This stuff was not even halfway done. Further send PRs with changes on multiple plugins.

**Comment by ManuelSchneid3r** [comment]
Didnt check the VPN plugin. please talk to @Bierchermuesli if you want some of your changes in the final VPN plugin

**Comment by roman-acumen** [comment]
@ManuelSchneid3r , I'm sorry, but have not modified the plugins, only covnered from previous infra to new one, using the same original code. Both extentions work, including the VPN one, as I use them both from my repo in day to day basis

**Comment by ManuelSchneid3r** [comment]
Metadata was not complete. dbus  is not on pypi. segfaults when quitting Albert and timers are running. Srsly when releasing stuff and shipping it with Albert it should be polished and well tested

**Pull request closed without merging**
