### PR TITLE
Adding clipboard support using copyq

### PR DESCRIPTION
**Pull request by raghuramos1987**
Is there a way I can get the "Amount of results" setting in python? I could use that to limit the number of items in the for loop to just get the right number.

### CODE REVIEW

**Comment by ManuelSchneid3r** [comment]
Stooop  :D we have 4 versions of CQ now :D

**Comment by raghuramos1987** [comment]
Oh! I did not know that. We can close this one then. Is there documentation on how to use the others?

**Comment by ManuelSchneid3r** [comment]
There is not much to document type `cq` to see the entries and and an optional filter to filter them

**Comment by benedictdudel** [comment]
@raghuramos1987 If you would like to contribute further please have a look at the following [pull request](https://github.com/albertlauncher/python/pull/1) and give some feedback if you like to :)

**Comment by raghuramos1987** [comment]
will do @benedictdudel !

**Pull request closed without merging**
