### PR TITLE
Add stadia plugin as submodule

### PR DESCRIPTION
**Pull request by sebastiansam55**

### CODE REVIEW

**Comment by sebastiansam55** [comment]
I think I did it right? Not a git expert.

**Comment by ManuelSchneid3r** [comment]
fatal: repository 'https://github.com/sebastiansam55/python/tree/master_stadia_submodule/' not found

**Comment by ManuelSchneid3r** [comment]
1. create a repo [1] containing your python extension
2. clone/pull the python repo [2]
3. add a submodule in [2] pointing to [1]
4. commit, push, send PR [2]

**Comment by ManuelSchneid3r** [comment]
Somehow your git submodules is not properly linked. Check your own repo and compare to xkcd and jetbrains.

**Comment by ManuelSchneid3r** [comment]
https://github.com/sebastiansam55/stadia-albert-plugin/blob/master/__init__.py#L21

Please use your github username for easy mentions.

**Comment by ManuelSchneid3r** [comment]
0.18 is out. Please check the [new api](https://github.com/albertlauncher/plugins/blob/master/python/README.md) . Do you mind to volunteer as a maintainer for the plugin?

**Comment by sebastiansam55** [comment]
Stadia is dead as of January 2023, no point to this plugin or whatever it
was.

**Comment by ManuelSchneid3r** [comment]
> or whatever it was.

everything okay? I hope you did not take it personally that I had no time to merge it. I thought I'd release 0.18 next month. for like two years now. I'm sorry about that. 

I dont know what Stadia actually is, but if you say so (as author) I guess it is fine to close this PR.

**Comment by sebastiansam55** [comment]
nah no worries, just didn't know the correct terminology this project uses

**Pull request closed without merging**
