### PR TITLE
[window_switcher:1.1] support global query

### PR DESCRIPTION
**Pull request by talengu**

### CODE REVIEW

**Comment by ManuelSchneid3r** [comment]
I am not really a friend of the shipped icons. there is the [freedesktop icon lookup](https://specifications.freedesktop.org/icon-theme-spec/latest/ar01s05.html) for such things. albert [implements](https://github.com/albertlauncher/albert/blob/master/include/albert/extensions/item.h#L33) it.

**Comment by talengu** [comment]
Nice. XDG is a good way, but lots of icon can not be found. Do we have icon_lookup fun to return false , then start using shipped icons ?

**Comment by talengu** [comment]
> I am not really a friend of the shipped icons. there is the [freedesktop icon lookup](https://specifications.freedesktop.org/icon-theme-spec/latest/ar01s05.html) for such things. albert [implements](https://github.com/albertlauncher/albert/blob/master/include/albert/extensions/item.h#L33) it. this way the users icon theme is taken into account. iirc [older](https://github.com/albertlauncher/python/blob/master/.archive/window_switcher/__init__.py) version supported this. well they used `iconlookup()` in the old api.

Nice. XDG is a good way, but lots of icon can not be found. Do we have icon_lookup fun to return false , then start using shipped icons ?

**Comment by ManuelSchneid3r** [comment]
> Nice. XDG is a good way, but lots of icon can not be found. Do we have icon_lookup fun to return false , then start using shipped icons ?

they are tried in the order you provide them in this url list. but actually every window should have an icon. which ones are not found?

**Comment by ManuelSchneid3r** [comment]
> Do we have icon_lookup fun to return false

note that we dont have icon_lookup fun at all. 0.18 (iirc) began making use of a[n icon url list in item](https://github.com/albertlauncher/albert/blob/master/include/albert/extensions/item.h#L31-L37).

**Comment by talengu** [comment]
> > Do we have icon_lookup fun to return false
> 
> note that we dont have icon_lookup fun at all. 0.18 (iirc) began making use of a[n icon url list in item](https://github.com/albertlauncher/albert/blob/master/include/albert/extensions/item.h#L31-L37).


vscode , virtual box, and ubuntu defaults and so on. 
image

**Comment by ManuelSchneid3r** [comment]
See here https://github.com/albertlauncher/python/blob/master/.archive/window_switcher/__init__.py#L38 this probably works

every app comes with an icon installed. therefore this should work. Shipping icons is not generalizing well.

**Comment by ManuelSchneid3r** [comment]
See also

**Comment by luutuankiet** [comment]
hey! any chance I can add this plugin this from source to test out ?

**Comment by talengu** [comment]
> hey! any chance I can add this plugin this from source to test out ? 
> 
> EDIT : nvm got that to work. looking forward to this being merged !

I do not have free time to find a good way of icon lookup func.🥹
Work is eating me！

**Comment by ManuelSchneid3r** [comment]
Icon lookup is built in. Just use the xdg URL scheme. Like "xdg:<appname>"

**Comment by talengu** [comment]
> Icon lookup is built in. Just use the xdg URL scheme. Like `xdg:<appname>`

OK

**Comment by PC-02** [comment]
built the project from source and loaded this plugin, albert throws this warning and doesn't seem to load the plugin, am I doing something wrong? 
```
02:05:35 [warn:python] Plugin invalid: Incompatible major interface version. Expected 1, got 0. (/home/pc/.local/share/albert/python/plugins/window_switcher)
```

**Comment by ManuelSchneid3r** [comment]
0.21 on master is not released yet. Get the pre-built one or build the latest tag

**Comment by PC-02** [comment]
building from the latest tag got it working, thank you!

**Comment by talengu** [comment]
how to do not use Triggers in python plugins ? https://github.com/albertlauncher/python/issues/170

Now python plugins support global trigger? And how to support?
image

**Comment by talengu** [comment]
nice!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
image

**Comment by talengu** [comment]
> > Icon lookup is built in. Just use the xdg URL scheme. Like `xdg:<appname>`
> 
> OK, I have changed it to the ` xdg:<appname>` func and test it well.
> 
> if someone likes, here is the window_switcher [backup](https://github.com/albertlauncher/python/files/11645866/window_switcher.tar.gz) using the "the shipped icons". [window_switcher.tar.gz](https://github.com/albertlauncher/python/files/11645866/window_switcher.tar.gz)

here is the window_switcher with some icons  support albert 0.21.1

[window_switcher1.1.tar.gz](https://github.com/albertlauncher/python/files/12186134/window_switcher.tar.gz)

**Comment by Base-115** [comment]
Hi, talengu.

I am testing the plugin and I want provide some feedback, if it will be useful.

The plugin working well, but

1 - Sometimes I can see the terminal flash quickly when the switching is performing;

2 - Sometimes, the window is bring to front, but the focus is not give, so I need repeat the act in Albert one more time or many times until switch to window.

3 - Switch to window take some time compared with ULauncher and KRunner (native Launcher in KDE Desktop).

**Comment by ManuelSchneid3r** [comment]
sorry for beaking things. please rebase. pyapi 2.0 is done. see the [stub](https://github.com/albertlauncher/python/blob/55524286ea61abc51d3ef8d5043b08eee35cffd9/albert.pyi). f 


> 1 - Sometimes I can see the terminal flash quickly when the switching is performing;
use [this](https://albertlauncher.github.io/reference/namespacealbert.html#ac85cded09e6e136185a21835c627754c)

**Comment by Base-115** [comment]
Hi, Manuel.

Sorry, I didn't understand what I should do about stuff that you sent, 😅.

Should replace something, is it?

**Comment by ManuelSchneid3r** [comment]
I just pushed some new stuff. you have to `git rebase master`

**Comment by ManuelSchneid3r** [comment]
talengu can you please reabase and make it python api 2.0 ready?

**Comment by talengu** [comment]
oops! git rebase faliled , and the api is changing too fast!  But, I will learn it. :smile_cat:

**Comment by ManuelSchneid3r** [comment]
Thats just an unfortunate time atm. usually the api does not change over years. move the directory of your plugin outside the plugin dir for a moment an do `git reset --hard`. note that this will undo all changes. so if you have other plugins there backup or move them as well.

**Comment by talengu** [comment]
> did you close this pr intentionally?

No，I will pull it when fixed.

**Comment by ManuelSchneid3r** [comment]
please get it upstream.

**Comment by talengu** [comment]
Hi, New albert can not run OK in my OS. ===>

https://github.com/albertlauncher/albert/issues/1289#issuecomment-1683926652


`git checkout tags/v0.21.1` work nice for me
but failed in the newest one : c66596e31336d1ed6e310d53b8f8cc6488aedf15

https://github.com/albertlauncher/albert/issues/1289#issuecomment-1683935605

**Comment by ManuelSchneid3r** [comment]
Have you installed all the required dependencies?

**Comment by ManuelSchneid3r** [comment]
If you don't develop native plugins you could also just install the prebuilt packages

**Comment by ManuelSchneid3r** [comment]
Please continue any discussion here: https://github.com/orgs/albertlauncher/discussions/1296

**Pull request closed without merging**
