### PR TITLE
Add Number Converter plugin

### PR DESCRIPTION
**Pull request by mparati31**

### CODE REVIEW

**Comment by ManuelSchneid3r** [comment]
Like this https://github.com/albertlauncher/python/tree/master/base_converter?

**Comment by mparati31** [comment]
Yes, very similar

**Comment by ManuelSchneid3r** [comment]
I appreciate your time, but why should I merge this introducing a duplicate and confusing users, which are already annoyed by the weak UX considering plugin management?

**Comment by ManuelSchneid3r** [comment]
Don't you think improving existing extensions makes more sense?

**Comment by mparati31** [comment]
I agree, I didn't realize there was already an extension that did the same thing.

**Pull request closed without merging**
