### PR TITLE
Protect window_switcher from split errors

### PR DESCRIPTION
**Pull request by xdg**
This commit stops window_switcher from erroring when the wm_class has
more or less than a single `.` character.  For example, here are two
problematic lines of outputs from `wmctrl -l -x` where the `wm_class` is
`N/A` or `rufus-3.17.exe.rufus.3.17.exe` (from Wine):

    0x01a00078  1 N/A                            remus Ozone X11
    0x03e00003  2 rufus-3.17.exe.rufus-3.17.exe  remus Rufus 3.17.1846

If there are no dots, the entry is skipped and not matched.  If there is
more than one dot, the part before the first dot is used for the display
name (e.g. "rufus-3").

### CODE REVIEW

**Comment by ManuelSchneid3r** [comment]
@edjoperez @dshoreman can you please review?

**Comment by xdg** [comment]
Ping. This has been open for a couple months.  I'm sure people are busy, but would it possible to get a review soon, please?  It's only ~20 lines and half of it is a comment explaining the behavior.

**Review by tomsquest — APPROVED** [review]

**Comment by tomsquest** [comment]
LGTM

**Comment by ManuelSchneid3r** [comment]
The 0.18 release will probably need changes. Since there will be no release in between I'll wait with the merge. Ty for your time. Ill comment when the it is released

**Comment by ManuelSchneid3r** [comment]
0.18 is out. Please check the [new api](https://github.com/albertlauncher/plugins/blob/master/python/README.md) . Do you mind to volunteer as a maintainer for the plugin?

**Comment by xdg** [comment]
I'm not really a Python person, nor do I have the time to maintain it even if I did. I was really just hoping to get this tiny change applied.

**Comment by ManuelSchneid3r** [comment]
neither am i, iirc i did not even write this code. thats why these plugins badly need maintainers.

**Comment by dshoreman** [comment]
> @edjoperez @dshoreman can you please review?

It's been over a year, but if my two cents are still desired I would probably move most of the new code into the `parseWindow` method, potentially modifying the named tuple to have an extra key or two if needed. That would allow the loop itself to stay (relatively) clean/simple and keeping all the parsing bits in one place.

I won't be able to test though, unfortunately. While I did contribute several fixes to this plugin via a partial rewrite in ed2778c9f1f687e3c6f46d01ee837b698e791102, that was back when it was advertised as GPL and I have since moved to an alternative launcher. Sorry I haven't had the time to respond sooner.

**Comment by MABIY** [comment]
please continue

**Comment by ManuelSchneid3r** [comment]
> I'm not really a Python person, nor do I have the time to maintain it even if I did. I was really just hoping to get this tiny change applied.

The problem today is that this code is incompatible with recent versions of albert. Ill close this PR since this plugin has been not been ported yet. 

Id appreciate if anybody actually using it could port it.

Regards

**Comment by ManuelSchneid3r** [comment]
Please continue any discussion here: https://github.com/orgs/albertlauncher/discussions/1296

**Comment by ManuelSchneid3r** [comment]
Please continue any discussion here: https://github.com/orgs/albertlauncher/discussions/1299

**Pull request closed without merging**
