### PR TITLE
Add window switcher for GNOME on Wayland

### PR DESCRIPTION
**Pull request by vlktomas**
Inspired by https://github.com/adrienverge/gnome-magic-window

### CODE REVIEW

**Comment by ManuelSchneid3r** [comment]
Why have you closed this one?

**Comment by vlktomas** [comment]
In Gnome 42 it is no longer possible to call `org.gnome.Shell.Eval` to get opened windows (see https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/7298ee23e91b756c7009b4d7687dfd8673856f8b) and I didn't find a workaround for that.

**Comment by ManuelSchneid3r** [comment]
Mhm i see. Thank you for your time

**Comment by ManuelSchneid3r** [comment]
Please continue any discussion here: https://github.com/orgs/albertlauncher/discussions/1299

**Pull request closed without merging**
