### PR TITLE
Added QR code extension as submodule

### PR DESCRIPTION
**Pull request by earthplusthree**

### CODE REVIEW

**Comment by ManuelSchneid3r** [comment]
this PR is somehow broken. no folder with the module there

**Comment by butforme** [comment]
Should be fixed now!

**Comment by ManuelSchneid3r** [comment]
0.18 is out. Please check the [new api](https://github.com/albertlauncher/plugins/blob/master/python/README.md) . Do you mind to volunteer as a maintainer for the plugin?

**Comment by ManuelSchneid3r** [comment]
Also please check [this comment](https://github.com/albertlauncher/python/pull/129#issuecomment-1372732334)

**Comment by ManuelSchneid3r** [comment]
@earthplusthree are you still interested in getting this plugin upstream?

**Comment by ManuelSchneid3r** [comment]
I am going to close this PR. It is not that I dont want this to be shipped upstream, but, as is, it cant be merged due to conflicts. Users/devs get the impression that I dont want to merge plugins, probably simply due to the amount of open PRs.  Also it's cumbersome for me to repeatedly iterate all these abandoned and stale PRs. Note that I am still interested in merging an up to date version of this plugin and I still get notifications. So if you want something to happen leave a comment or simply open a new PR.

**Pull request closed without merging**
