### PR TITLE
Add an extension to generate UUID v4

### PR DESCRIPTION
**Pull request by mkobayashime**
Thanks a lot for the software.

Add uuid generator extension.
It's based on the one that has pull requested (#68) by @jtcrank 2 years ago.

### CODE REVIEW

**Comment by mkobayashime** [comment]
@ManuelSchneid3r 
Could you take a look at this PR, or invite some other reviewers?

**Comment by ManuelSchneid3r** [comment]
0.18 is out. Please check the [new api](https://github.com/albertlauncher/plugins/blob/master/python/README.md) . Do you mind to volunteer as a maintainer for the plugin?

**Comment by ManuelSchneid3r** [comment]
?

**Comment by mkobayashime** [comment]
@ManuelSchneid3r My apologies for closing this without explanation. I'm not using Albert anymore, and thus won't be able to maintain the extension.

**Pull request closed without merging**
