### PR TITLE
fix jetbrains recents parsing for 2019.3 eap

### PR DESCRIPTION
**Pull request by iyzana**

### CODE REVIEW

**Comment by succcubbus** [comment]
The EAP version started generating xml that looks like this:
```xml
...
<RecentProjectMetaInfo projectWorkspaceId="...">
  <option name="binFolder" value="$APPLICATION_HOME_DIR$/bin" />
  <option name="build" value="IU-193.3519.25" />
  <option name="buildTimestamp" value="1568822400642" />
  <option name="eap" value="true" />
  <frame x="17" y="17" width="933" height="1046" extendedState="6" />
  <option name="productionCode" value="IU" />
  <option name="projectOpenTimestamp" value="1569415744426" />
</RecentProjectMetaInfo>
...
```

and the `frame` key does not have a `name` attribute, so the script would fail.

**Comment by mqus** [comment]
That explains it, thanks!

**Comment by mqus** [comment]
(In case you are wondering why nothing is happening here, I don't have any merge rights, so we have to wait for @ManuelSchneid3r to merge this)

**Comment by succcubbus** [comment]
i figured, i've had https://github.com/albertlauncher/python/pull/64 open for ~7 months now

**Comment by Sharsie** [comment]
@iyzana thanks for this, before it gets merged, it may be safer to just check for existence of the attribute, rather than the tag name (in case JB decides to use <option> without a name for something else in the future)
something alone the lines of
```diff
-                if o.tag == 'option' and o.attrib["name"] == 'projectOpenTimestamp':
+                if 'name' in o.attrib and o.attrib["name"] == 'projectOpenTimestamp':
```

or a combination of both

**Comment by iyzana** [comment]
@Sharsie yeah, probably a good idea. done

**Comment by mqus** [comment]
Short notice for everyone who is interested: I made a few more fixes to the plugin and am now hosting the plugin here: https://github.com/mqus/jetbrains-albert-plugin

**Comment by ManuelSchneid3r** [comment]
> Short notice for everyone who is interested: I made a few more fixes to the plugin and am now hosting the plugin here: https://github.com/mqus/jetbrains-albert-plugin

please upstream. i you like owning your own repo you could also make a submodule

**Pull request merged**
