### PR TITLE
VSCode workspace plugin

### PR DESCRIPTION
**Pull request by lawrencegripper**
A simple plugin to list and launch recent VSCode workspaces

(Yeah the grep is horrible but there isn't a way to list this exposed via code CLI and grep works)

### CODE REVIEW

**Comment by Bierchermuesli** [comment]
maybe just load the `~/.config/Code/User: vi globalStorage/storage.json ` instead of grep?

have a look on this existing plugin: https://github.com/Bierchermuesli/albert-vscode/tree/main (PR pending)

**Comment by ManuelSchneid3r** [comment]
hey @bierchermuesli, which PR are you talking of? did I miss something?

**Comment by Bierchermuesli** [comment]
> hey @Bierchermuesli, which PR are you talking of? did I miss something?

my fork into https://github.com/mparati31/albert-vscode , sorry about the confusion.  Would you suggest a PR into [albertlauncher/python](https://github.com/albertlauncher/python) ?

**Comment by ManuelSchneid3r** [comment]
I am not that satisfied with either of them. Some ideas:

* this pr is lean. i really like the minmalism. but…
* grep is suboptimal, because it probably is not portable to other platforms. I dont understand the grep arguments, but if it just reads the file and finds pattern this should be solvable with pure python unsing regexes right?
* mparati's approach looks bloaty in comparison.
* IndexQueryHandler could be used with a hook into GlobalQueryHandler.handleQuery which checks the mdate of the file,builds a new index if it is newer and then relays to IndexQueryHandler.handleQuery. This way we get the global query handling, fuzzy search and the file will not be permanently read again. also response times are way faster, while this bunch of items should have a negligible memory impact.

**Comment by lawrencegripper** [comment]
@ManuelSchneid3r thanks for :eyes: - like these ideas :+1: 

I'll try and get some time to move over to python regex and `IndexQueryHandler` approach. 

Others are welcome to pick this up ahead of me if they have more time.

**Comment by ManuelSchneid3r** [comment]
This issue was not intentionally but automatically closed because I renamed the master branch to main. If you are still interested in getting it merged please reopen against `main`.

**Pull request closed without merging**
